let SuspensionAndBrakesDB = [
  {
    id: 1,
    title: "Rear Brake Pads Genuine Parts Toyota Corolla South Africa 28-2",
    price: "26",
    imageUrl: "images/brea1.jpg",
    qty: 1,
  },
  {
    id: 2,
    title: "Rear Brake Pads Toyota Corolla Gulf Genuine Parts 28-2013",
    price: "1850",
    imageUrl: "images/brea2.jpg",
    qty: 1,
  },
  {
    id: 3,
    title: "Front Brake Pads Toyota Corolla South Africa Genuine Parts 28-",
    price: "1450",
    imageUrl: "images/brea3.jpg",
    qty: 1,
  },
  {
    id: 4,
    title: "Rear Brake Pads Toyota Genuine Parts 27-2017",
    price: "660",
    imageUrl: "images/brea4.jpg",
    qty: 1,
  },
  {
    id: 5,
    title: "Front Brake Pads Toyota Corolla Gulf Genuine Parts 28-20",
    price: "2150",
    imageUrl: "images/brea5.jpg",
    qty: 1,
  },
  {
    id: 6,
    title: "Front Brake Pads Toyota Land Cruiser Genuine Parts 27-2018",
    price: "1550",
    imageUrl: "images/brea6.jpg",
    qty: 1,
  },
  {
    id: 7,
    title: "Front Brake Pads Toyota AVENSIS Genuine Parts 26-2010",
    price: "1350",
    imageUrl: "images/brea7.jpg",
  },
  {
    id: 10,
    title: "Front Brake Pads Toyota CH-R Genuine Parts 2017-2018",
    price: "1950",
    imageUrl: "images/brea8.jpg",
    qty: 1,
  },
  {
    id: 11,
    title: "Rear Brake Pads Toyota LAND CRUISER Genuine Parts 28-2015",
    price: "950",
    imageUrl: "images/brea9.jpg",
    qty: 1,
  },
  {
    id: 12,
    title: "Rear brake bads G L O R Y for Toyota Corolla Turkey 2014-2018",
    price: "225",
    imageUrl: "images/pr1.jpg",
    qty: 1,
  },
  {
    id: 13,
    title: "Rear brake bads G L O R Y for Toyota Yaris-corolla 25-2014",
    price: "240",
    imageUrl: "images/pr2.jpg",
    qty: 1,
  },
  {
    id: 14,
    title: "Rear brake bads G L O R Y for Toyota Corolla 1992-20",
    price: "150",
    imageUrl: "images/pr3.jpg",
    qty: 1,
  },
  {
    id: 15,
    title: "Rear brake bads G L O R Y for Toyota Avanza 27-2018",
    price: "320",
    imageUrl: "images/pr4.jpg",
    qty: 1,
  },
  {
    id: 16,
    title: "Front Brake Pads G L O R Y for Toyota Yaris 2014-2019",
    price: "184",
    imageUrl: "images/pr5.jpg",
    qty: 1,
  },
  {
    id: 17,
    title: "Front Brake Pads G L O R Y for Toyota Yaris 25-2014",
    price: "225",
    imageUrl: "images/pr6.jpg",
    qty: 1,
  },
  {
    id: 20,
    title: "Front Brake Pads G L O R Y for Toyota Corolla 1992-20",
    price: "234",
    imageUrl: "images/pr7.jpg",
    qty: 1,
  },
  {
    id: 21,
    title: "Front Brake Pads G L O R Y for Toyota Corolla 2014-2018",
    price: "245",
    imageUrl: "images/pr8.jpg",
    qty: 1,
  },
  {
    id: 22,
    title: "Front Brake Pads G L O R Y for Toyota Corolla 28-2010",
    price: "567",
    imageUrl: "images/pr9.jpg",
    qty: 1,
  },
  {
    id: 23,
    title: "Original Rear Shock Absorbe Toyota Corolla 21-27",
    price: "2250",
    imageUrl: "images/help1.jpg",
    qty: 1,
  },
  {
    id: 24,
    title: "Original Rear Shock Absorber Toyota Yaris 2014-2017",
    price: "1250",
    imageUrl: "images/help2.jpg",
    qty: 1,
  },
  {
    id: 25,
    title: "Original Right Front Shock Absorbe Toyota Corolla 21-27",
    price: "22",
    imageUrl: "images/help3.jpg",
    qty: 1,
  },
  {
    id: 26,
    title: "Original Left Front Shock Absorbe Toyota Corolla 21-27",
    price: "22",
    imageUrl: "images/help4.jpg",
    qty: 1,
  },
  {
    id: 27,
    title: "Original Right Front Shock Absorber Toyota Yaris 26-2011",
    price: "22",
    imageUrl: "images/help5.jpg",
    qty: 1,
  },
  {
    id: 30,
    title: "Original Left Front Shock Absorber Toyota Yaris 26-2011",
    price: "22",
    imageUrl: "images/help6.jpg",
    qty: 1,
  },
  {
    id: 31,
    title: "Original Front Shock Absorbe Toyota Yaris 2014-2017",
    price: "22",
    imageUrl: "images/help7.jpg",
    qty: 1,
  },
  {
    id: 32,
    title: "Original CV Joint Toyota Yaris 2014-2017 Available",
    price: "65",
    imageUrl: "images/help8.jpg",
    qty: 1,
  },
  {
    id: 33,
    title: "Original Front Coil Spring Toyota Yaris 2014-2017",
    price: "660",
    imageUrl: "images/help9.jpg",
    qty: 1,
  },
];

localStorage.setItem(
  "SuspensionAndBrakes",
  JSON.stringify(SuspensionAndBrakesDB)
);

let enginePartsDB = [
  {
    id: 34,
    title: "Toyota Fortuner Maintenance Package 2018-2021 - 40CC V6",
    price: 3640,
    imageUrl: "images/pack1.jpg",
    qty: 1,
  },
  {
    id: 35,
    title: "Toyota Fortuner Maintenance Package 2011-2017 - 40CC V6",
    price: 4725,
    imageUrl: "images/pack2.jpg",
    qty: 1,
  },
  {
    id: 36,
    title: "Toyota Fortuner Maintenance Package 2018-2021 - 27CC",
    price: 3070,
    imageUrl: "images/pack3.jpg",
    qty: 1,
  },
  {
    id: 37,
    title: "Toyota Fortuner Maintenance Package 2011-2017 - 27CC",
    price: 35,
    imageUrl: "images/pack4.jpg",
    qty: 1,
  },
  {
    id: 40,
    title: "Corolla Gulf Maintenance Package engine japan 2011-2013",
    price: 2455,
    imageUrl: "images/pack5.jpg",
    qty: 1,
  },
  {
    id: 41,
    title: "Fuel Pump Assembly for toyota corolla 28-2013",
    price: 39,
    imageUrl: "images/pack6.jpg",
    qty: 1,
  },
  {
    id: 42,
    title: "Fuel Pump Assembly for toyota avanza 25-2011",
    price: 19,
    imageUrl: "images/pack7.jpg",
    qty: 1,
  },
  {
    id: 43,
    title: " Fuel Pump Assembly for toyota yaris 2014-2019",
    price: 3445,
    imageUrl: "images/pack8.jpg",
    qty: 1,
  },
  {
    id: 44,
    title: " Fuel Pump Assembly for toyota camry 2011-2017",
    price: 39,
    imageUrl: "images/pack9.jpg",
    qty: 1,
  },
  {
    id: 45,
    title: "Radiator Toyota Hiace 25-2012",
    price: 19,
    imageUrl: "images/rediator",
    qty: 1,
  },
  {
    id: 46,
    title: "Radiator Toyota Hiace 2012-2016",
    price: 2350,
    imageUrl: "images/rediator",
    qty: 1,
  },
  {
    id: 47,
    title: "Radiator Toyota Hilux diesel 2016-2020",
    price: 17,
    imageUrl: "images/rediator",
    qty: 1,
  },
  {
    id: 50,
    title: "Radiator Toyota yaris sedan 2014-2019",
    price: 10,
    imageUrl: "images/rediator",
    qty: 1,
  },
  {
    id: 51,
    title: "Radiator Toyota fortuner 2018-2020",
    price: 2350,
    imageUrl: "images/rediator",
    qty: 1,
  },
  {
    id: 52,
    title: "Radiator Toyota Hilux petrol 26-2015",
    price: 1750,
    imageUrl: "images/rediator",
    qty: 1,
  },
  {
    id: 53,
    title: "Radiator Toyota fortuner 2011-2017",
    price: 20,
    imageUrl: "images/rediator",
    qty: 1,
  },
  {
    id: 54,
    title: " Radiator Toyota Hilux diesel 26-2015",
    price: 1550,
    imageUrl: "images/rediator",
    qty: 1,
  },
  {
    id: 55,
    title: "Radiator Toyota Corolla 28-2013",
    price: 990,
    imageUrl: "images/rediator",
    qty: 1,
  },
  {
    id: 56,
    title: "Radiator Automatic Toyota Corolla 21-27",
    price: 895,
    imageUrl: "images/red1.jpg",
    qty: 1,
  },
  {
    id: 57,
    title: "Radiator Manual Toyota Vigo____ 24-29",
    price: 1540,
    imageUrl: "images/red2.jpg",
    qty: 1,
  },
  {
    id: 60,
    title: "Radiator Automatic Toyota HILUX 25-2016",
    price: 2060,
    imageUrl: "images/red3.jpg",
    qty: 1,
  },
  {
    id: 61,
    title: "Water Pump for Toyota Corolla 7A Police 1996-21",
    price: 490,
    imageUrl: "images/wp1.jpg",
    qty: 1,
  },
  {
    id: 62,
    title: "Water Pump for Toyota Corolla 3K 1975-1978",
    price: 325,
    imageUrl: "images/wp2.jpg",
    qty: 1,
  },
  {
    id: 63,
    title: "Water Pump for Toyota Starlet 3K,4K 1977-1980",
    price: 360,
    imageUrl: "images/wp3.jpg",
    qty: 1,
  },
  {
    id: 64,
    title: "Water Pump for Toyota Corolla 4K 1983-1985",
    price: 370,
    imageUrl: "images/wp4.jpg",
    qty: 1,
  },
  {
    id: 65,
    title: "Water Pump for Toyota Corolla ___ 1983-1986",
    price: 385,
    imageUrl: "images/wp5.jpg",
    qty: 1,
  },
  {
    id: 66,
    title: "Water Pump for Toyota Corolla 2E / 1988-1994",
    price: 335,
    imageUrl: "images/wp6.jpg",
    qty: 1,
  },
  {
    id: 67,
    title: "Water Pump for Toyota Corolla 2E 1994-1999",
    price: 475,
    imageUrl: "images/wp7.jpg",
    qty: 1,
  },
  {
    id: 70,
    title: "Water Pump for Toyota Avanza___ 27,2012",
    price: 470,
    imageUrl: "images/wp8.jpg",
    qty: 1,
  },
  {
    id: 71,
    title: "Water Pump for Toyota Brand__-_-__-__-GMB",
    price: 415,
    imageUrl: "images/wp9.jpg",
    qty: 1,
  },
  {
    id: 72,
    title: "Water____ Pump____ for____ Toyota____ Corolla",
    price: 460,
    imageUrl: "images/wp10.jpg",
    qty: 1,
  },
  {
    id: 73,
    title: "Water Pump for Toyota Corolla ZZFE 28/2013",
    price: 565,
    imageUrl: "images/wp11.jpg",
    qty: 1,
  },
  {
    id: 74,
    title: "Water Pump for Toyota Hiace Diesel 25,2012 - 2KDFT/1KZ",
    price: 325,
    imageUrl: "images/wp12.jpg",
    qty: 1,
  },
  {
    id: 75,
    title: "Water Pump for Toyota Hilux vigo 25,2010 - 2KD",
    price: 545,
    imageUrl: "images/wp13.jpg",
    qty: 1,
  },
  {
    id: 76,
    title: "Water Pump for Toyota Hilux 12R 1975-1983",
    price: 440,
    imageUrl: "images/wp14.jpg",
    qty: 1,
  },
  {
    id: 77,
    title: "Water Pump for Toyota Hiace 3,5L Diesel 1990/1999",
    price: 370,
    imageUrl: "images/wp15.jpg",
    qty: 1,
  },
  {
    id: 101,
    title: "Rear Engine Mount Toyota Corolla 28-2013",
    price: 250,
    imageUrl: "images/mo1.jpg",
    qty: 1,
  },
  {
    id: 102,
    title: "Engine Mount Toyota Corolla_____ 21-27",
    price: 175,
    imageUrl: "images/mo2.jpg",
    qty: 1,
  },
  {
    id: 103,
    title: "Rear Engine Mount Toyota Corolla 1988-1991",
    price: 245,
    imageUrl: "images/mo4.jpg",
    qty: 1,
  },
  {
    id: 104,
    title: "Engine Mount Toyota Corolla_____ 21-27",
    price: 335,
    imageUrl: "images/mo3.jpg",
    qty: 1,
  },
  {
    id: 105,
    title: "Front Engine Mount Toyota Corolla 28-2013",
    price: 2,
    imageUrl: "images/mo5.jpg",
    qty: 1,
  },
  {
    id: 106,
    title: "Front Engine Mount Toyota Corolla 28-2013",
    price: 3,
    imageUrl: "images/mo6.jpg",
    qty: 1,
  },
  {
    id: 107,
    title: "Front Engine Mount Toyota Corolla 21-27",
    price: 225,
    imageUrl: "images/mo7.jpg",
    qty: 1,
  },
  {
    id: 110,
    title: "Front Engine Mount Toyota Corolla 1993-20",
    price: 345,
    imageUrl: "images/mo8.jpg",
    qty: 1,
  },
  {
    id: 112,
    title: "Left and Right Ball Joint Toyota Corolla 1992-1995",
    price: 150,
    imageUrl: "images/mo9.jpg",
    qty: 1,
  },
  {
    id: 113,
    title: "Rear Wheel hub Toyota Yaris_____ 27-2014",
    price: 315,
    imageUrl: "images/mo10.jpg",
    qty: 1,
  },
  {
    id: 114,
    title: "Rear Wheel hub Toyota Corolla _____28-2013",
    price: 814,
    imageUrl: "images/mo11.jpg",
    qty: 1,
  },
  {
    id: 115,
    title: "Front Wheel Hub Toyota Corolla 28-2013",
    price: 750,
    imageUrl: "images/mo12.jpg",
    qty: 1,
  },
];
// localStorage.setItem('engineParts', JSON.stringify(enginePartsDB));

let mirrorsDB = [
  {
    id: 116,
    title: "Right Side Mirror Toyota Hiace____ 26-2016",
    price: 565,
    imageUrl: "images/mirror1.jpg",
    qty: 1,
  },
  {
    id: 117,
    title: "Left Side Mirror Toyota Hiace ____26-2016",
    price: 565,
    imageUrl: "images/mirror2.jpg",
    qty: 1,
  },
  {
    id: 118,
    title: "Right Side Mirror Power Toyota Corolla 25-27",
    price: 385,
    imageUrl: "images/mirror3.jpg",
    qty: 1,
  },
  {
    id: 119,
    title: "Left Side Mirror Power Toyota Corolla 25-27",
    price: 385,
    imageUrl: "images/mirror4.jpg",
    qty: 1,
  },
  {
    id: 120,
    title: "Left Side Mirror Power with Turn Signal Lamp Toyota Corolla",
    price: 650,
    imageUrl: "images/mirror5.jpg",
    qty: 1,
  },
  {
    id: 121,
    title: "Right Side Mirror Power with Turn Signal Lamp Toyota Corolla",
    price: 605,
    imageUrl: "images/mirror6.jpg",
    qty: 1,
  },
  {
    id: 122,
    title: "Right Side Mirror Power with Turn Signal Lamp Toyota Avensis",
    price: 15,
    imageUrl: "images/mirror7.jpg",
    qty: 1,
  },
  {
    id: 123,
    title: "Left Side Mirror Power with Turn Signal Lamp Toyota Avensis 2",
    price: 15,
    imageUrl: "images/mirror8.jpg",
    qty: 1,
  },
  {
    id: 124,
    title: "Left Side Mirror Toyota Avensis_____ 29-2012",
    price: 1075,
    imageUrl: "images/mirror9.jpg",
    qty: 1,
  }
];
